# Define the API version and kind of resource
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog # Name of the deployment
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      # Label to identify the app
      app: book-catalog
  template:
    metadata:
      labels:
        # Label to identify the app
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        # Docker image to use
        image: book-catalog:1
        ports:
        - containerPort: 8000
        # Do not pull the image from a registry
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          # Database connection URL
          value: "postgresql://sit722_part2_l2gr_user:e5FCAXLXj0MM43p3n6H2XvGeIAdRaXUV@dpg-crtp1vm8ii6s73ah20o0-a.oregon-postgres.render.com/sit722_part2_l2gr"
---
# Define the API version and kind of resource
apiVersion: v1
kind: Service
metadata:
  # Name of the service
  name: book-catalog
spec:
  selector:
    # Label to identify the app
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # Node port to expose the service
      nodePort: 30000
